Repository depromeet/sulsul-FE, pull requests merged in 2022-04, with the labels that each got.

#1 초기 개발 설정
  .eslintignore
  .eslintrc
  .github/workflows/chromatic.yml
  .gitignore
  .prettierrc
  .storybook/main.js
  .storybook/preview.js
  next-env.d.ts
  next.config.js
  package.json
  src/components/Sample/Sample.stories.tsx
  src/components/Sample/Sample.tsx
  src/components/Sample/index.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/themes/GlobalStyle.tsx
  src/themes/index.ts
  src/types/emotion.d.ts
  tsconfig.json
  tsconfig.paths.json
  yarn.lock
Labels: good first issue

#3 chore: PR 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📖 documentation, priority:row, priority:medium, priority:high

#9 feature: SearchItem, SearchList 컴포넌트 구현
  .storybook/preview.js
  package.json
  src/assets/history.svg
  src/assets/icon.ts
  src/assets/search.svg
  src/components/search/SearchItem/SearchItem.stories.tsx
  src/components/search/SearchItem/SearchItem.tsx
  src/components/search/SearchItem/index.ts
  src/components/search/SearchList/SearchList.stories.tsx
  src/components/search/SearchList/SearchList.tsx
  src/components/search/SearchList/index.ts
  src/hooks/index.ts
  src/hooks/useSearchHistory.ts
  src/pages/_app.tsx
  src/recoil/atoms/index.ts
  src/recoil/atoms/searchHistories.ts
  src/recoil/effects/index.ts
  src/recoil/effects/persist.ts
  src/types/svg.d.ts
  yarn.lock
Labels: ✨ new feature
