Repository depromeet/sulsul-FE, pull requests merged in 2022-06, with the labels that each got.

#81 feat: 맥주 요청 완료 페이지 추가
  src/assets/film.svg
  src/assets/icon.ts
  src/containers/BeerRequestCompleteContainer/BeerRequestCompleteContainer.stories.tsx
  src/containers/BeerRequestCompleteContainer/BeerRequestCompleteContainer.tsx
  src/containers/BeerRequestCompleteContainer/index.ts
  src/pages/beer/request/complete.tsx
Labels: ✨ new feature

#79 feat: :sparkles: 공유하기 기능 추가
  package.json
  src/containers/BeerDetailContainer/BeerDetailContainer.stories.tsx
  src/containers/BeerDetailContainer/BeerDetailContainer.tsx
  src/pages/beer/[id].tsx
  src/utils/share.ts
  src/utils/toast.ts
  yarn.lock
Labels: ✨ new feature

#82 feat: 요청한 맥주 목록 아이템 UI 추가
  src/assets/barcode_vertical.svg
  src/assets/check_circle_outline.svg
  src/assets/chevron_down.svg
  src/assets/chevron_up.svg
  src/assets/icon.ts
  src/components/RequestedBeerItem/RequestedBeerItem.stories.tsx
  src/components/RequestedBeerItem/RequestedBeerItem.tsx
  src/components/RequestedBeerItem/index.ts
Labels: ✨ new feature

#83 feat: ✨ 기록 생성 완료 페이지 구현
  .eslintrc
  src/apis/record/create-record.ts
  src/apis/record/index.ts
  src/apis/record/record.ts
  src/components/BeerTicket/BeerTicket.stories.tsx
  src/components/BeerTicket/BeerTicket.tsx
  src/constants/Record.ts
  src/containers/CompletedRecordContainer/CompletedRecordContainer.stories.tsx
  src/containers/CompletedRecordContainer/CompletedRecordContainer.tsx
  src/containers/CompletedRecordContainer/index.ts
Labels: awesome beerair

#91 feat: 맥주 추천, 반한 맥주 탭 목록 페이지
  src/apis/beer.ts
  src/components/BeerList/BeerList.stories.tsx
  src/components/BeerList/BeerList.tsx
  src/components/BeerListPageHeader/BeerListPageHeader.tsx
  src/components/BeerSearchResultList/BeerSearchResultList.tsx
  src/components/BottomFloatingButtonArea/BottomFloatingButtonArea.tsx
  src/components/Header/Header.stories.tsx
  src/components/Header/extras/BeerListViewToggleButton.tsx
  src/components/Header/extras/extras.stories.tsx
  src/components/Header/extras/index.tsx
  src/components/beerItem/BeerListItem/BeerListItem.tsx
  src/components/commons/Button/Button.tsx
  src/containers/BeerListContainer/recoil/atoms/index.ts
  src/containers/BeerRecommendAndLikedContainer/BeerRecommendAndLikedContainer.stories.tsx
  src/containers/BeerRecommendAndLikedContainer/BeerRecommendAndLikedContainer.tsx
  src/containers/BeerRecommendAndLikedContainer/index.ts
  src/pages/beer/recommend-and-liked.tsx
  src/queries/index.ts
  src/queries/useGetBeersLiked.ts
  src/queries/useGetBeersRecommend.ts
  src/recoil/atoms/beerListViewType.ts
  src/recoil/atoms/index.ts
Labels: ✨ new feature

#93 feat: 맥주 개수 api 연동
  .gitignore
  package.json
  src/apis/beer.ts
  src/apis/continent.ts
  src/apis/country.ts
  src/components/BeerListFilterAndSorter/BeerListFilterAndSorter.tsx
  src/components/BeerSearchResultList/BeerSearchResultList.tsx
  src/components/beers-filter/BeerListFilterBottomSheet/BeerCountryFilterTab/BeerCountryFilterTab.tsx
  src/containers/BeerListContainer/BeerListContainer.tsx
  src/queries/index.ts
  src/queries/useGetBeerTypes.ts
  src/queries/useGetBeers.ts
  src/queries/useGetBeersCount.ts
  src/queries/useGetContinents.ts
  src/queries/useGetCountries.ts
  yarn.lock
Labels: ✨ new feature

#95 feat: ga 초기 설정 및 각 페이지별 view 측정
  package.json
  src/components/GTagScript/GTagScript.tsx
  src/components/GTagScript/index.ts
  src/configs/ga.ts
  src/constants/index.ts
  src/constants/page-titles.ts
  src/containers/BeerRecommendAndLikedContainer/BeerRecommendAndLikedContainer.stories.tsx
  src/containers/BeerRecommendAndLikedContainer/BeerRecommendAndLikedContainer.tsx
  src/containers/CreateRecordContainer/CreateRecordContainer.tsx
  src/hooks/index.ts
  src/hooks/useGtagPageView.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/beer/recommend-and-liked.tsx
  src/pages/beer/request/complete.tsx
  src/pages/beers/[id].tsx
  src/pages/beers/index.tsx
  src/pages/etc.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/onboarding.tsx
  src/pages/privacy-policy.tsx
  src/pages/profile.tsx
  src/pages/team.tsx
  src/pages/terms.tsx
  yarn.lock
Labels: ✨ new feature

#96 feature: 기록 페이지 - 초기 맥주 데이터 및 기록 api 연동
  next.config.js
  src/apis/beer.ts
  src/apis/record/create-record.ts
  src/components/LevelModal/LevelModal.tsx
  src/components/Modal/Modal.tsx
  src/components/ProfileModifyModal/ProfileModifyModal.tsx
  src/components/Review/Review.tsx
  src/components/Tab/Tab.tsx
  src/components/formFields/EmojiRadioField/EmojiRadioField.tsx
  src/components/formFields/EmojiRadioField/EmojiRadioGroup.tsx
  src/components/formFields/EmojiRadioField/EmojiTransitionViewer.tsx
  src/components/formFields/ImageUploadField/ImageUploadField.tsx
  src/components/formFields/MultiSelectField/MultiSelect.tsx
  src/components/formFields/MultiSelectField/MultiSelectField.tsx
  src/components/formFields/SelectField/SelectField.tsx
  src/configs/axios.ts
  src/containers/BeerDetailContainer/BeerDetailContainer.tsx
  src/containers/CreateRecordContainer/CreateRecordContainer.tsx
  src/containers/CreateRecordContainer/RecordThirdStepContainer/RecordThirdStepContainer.tsx
  src/pages/_app.tsx
  src/pages/record/create/[id].tsx
  src/queries/useGetBeer.ts
Labels: awesome beerair

#101 fix: :lipstick: 맥주 아이템 이미지 css 수정
  src/components/beerItem/BeerGridItem/BeerGridItem.tsx
  src/components/beerItem/BeerListItem/BeerListItem.tsx
Labels: 🐛 bug

#105 feat: ✨ my records 페이지에서 record ticket 상세페이지 연결!
  src/components/BottomNavigation/BottomNavigation.tsx
  src/components/RecordList/RecordList.tsx
  src/components/RecordListItem/RecordListItem.tsx
  src/containers/CompletedRecordContainer/index.ts
  src/containers/CreateRecordContainer/RecordThirdStepContainer/RecordThirdStepContainer.tsx
  src/containers/RecordTicketContainer/RecordTicketContainer.stories.tsx
  src/containers/RecordTicketContainer/RecordTicketContainer.tsx
  src/containers/RecordTicketContainer/index.ts
  src/containers/RecordsContainer/RecordsContainer.tsx
  src/pages/record/ticket/[id].tsx
Labels: awesome beerair

#104 feat: ✨ 맥주 티켓 저장 기능 구현
  package.json
  src/components/BeerTicket/BeerTicket.tsx
  src/containers/BeerDetailContainer/BeerDetailContainer.tsx
  src/containers/RecordTicketContainer/CreateImage.tsx
  src/containers/RecordTicketContainer/RecordTicketContainer.tsx
  src/containers/RecordTicketContainer/index.ts
  yarn.lock
Labels: ✨ new feature, awesome beerair

#77 feat: MultiImageUploadField 추가 (맥주 요청 페이지 컴포넌트)
  src/apis/upload/image-upload.ts
  src/assets/camera.svg
  src/assets/icon.ts
  src/components/formFields/MultiImageUploadField/MultiImageUploadField.stories.tsx
  src/components/formFields/MultiImageUploadField/MultiImageUploadField.tsx
  src/components/formFields/MultiImageUploadField/index.ts
Labels: ✨ new feature

#108 feat: :sparkles: 맥주 상세페이지 스크롤 인터랙션 구현
  src/components/Header/Header.tsx
  src/containers/BeerDetailContainer/BeerDetailContainer.tsx
Labels: awesome beerair

#117 feat: 로그인, 로그아웃, 회원탈퇴 api 연동
  src/apis/user/delete-user.ts
  src/apis/user/index.ts
  src/apis/user/update-user.ts
  src/components/ProfileModifyModal/ProfileModifyModal.tsx
  src/components/socialLoginButtons/KakaoLoginButton/KakaoLoginButton.tsx
  src/components/socialLoginButtons/NaverLoginButton/NaverLoginButton.tsx
  src/configs/axios.ts
  src/containers/EtcContainer/EtcContainer.tsx
  src/containers/OnBoardingContainer/OnBoardingContainer.tsx
  src/containers/ProfileContainer/ProfileContainer.tsx
  src/containers/SignUpContainer/SignUpContainer.tsx
  src/queries/index.ts
  src/queries/useDeleteUser.ts
Labels: ✨ new feature

#116 feat: :sparkles: 이용약관, 개인정보 처리방침 내용 추가
  contents/privacy-policy.md
  contents/terms-of-service.md
  next.config.js
  package.json
  src/components/Markdown/Markdown.tsx
  src/components/Markdown/index.ts
  src/constants/page-titles.ts
  src/containers/EtcContainer/EtcContainer.tsx
  src/containers/PrivacyPolicyContainer/PrivacyPolicyContainer.stories.tsx
  src/containers/PrivacyPolicyContainer/PrivacyPolicyContainer.tsx
  src/containers/PrivacyPolicyContainer/index.ts
  src/containers/ProfileContainer/ProfileContainer.tsx
  src/containers/TermsOfServiceContainer/TermsOfServiceContainer.stories.tsx
  src/containers/TermsOfServiceContainer/TermsOfServiceContainer.tsx
  src/containers/TermsOfServiceContainer/index.ts
  src/hooks/useGtagPageView.ts
  src/pages/profile/privacy-policy.tsx
  src/pages/profile/terms.tsx
  src/types/markdown.d.ts
  src/utils/parseMarkdown.ts
  yarn.lock
Labels: ✨ new feature

#134 feat: :lipstick: record ticket 이모지 추가, 첫번째 기록 비행기 추가
  public/images/airplane_top.svg
  src/assets/airplane_top.svg
  src/components/BeerTicket/BeerTicket.tsx
  src/components/HomeBeerTicket/HomeBeerTicket.tsx
  src/components/RecordList/RecordList.tsx
  src/components/RecordListItem/RecordListItem.tsx
  src/containers/HomeContainer/HomeContainer.tsx
  src/containers/RecordTicketContainer/RecordTicketContainer.tsx
Labels: awesome beerair

#132 feat: ✨ 맥주기록 삭제 api 연동 및 빈 티켓 UI 구현
  .storybook/main.js
  package.json
  public/images/no-record-ticket.png
  src/apis/record/index.ts
  src/apis/record/record.ts
  src/assets/delete.svg
  src/assets/icon.ts
  src/components/BeerTicket/BeerTicket.tsx
  src/components/BeerTicket/BeerTicketFlight.tsx
  src/components/BeerTicketTitle/BeerTicketTitle.tsx
  src/components/Header/extras/DeleteButton.tsx
  src/components/Header/extras/index.tsx
  src/components/commons/Button/Button.tsx
  src/containers/EtcContainer/EtcContainer.tsx
  src/containers/HomeContainer/HomeContainer.tsx
  src/containers/RecordTicketContainer/RecordTicketContainer.tsx
  src/containers/RecordsContainer/RecordsContainer.tsx
  src/queries/index.ts
  src/queries/useDeleteRecord.ts
  src/themes/index.ts
  src/utils/toast.ts
  yarn.lock
Labels: ✨ new feature

#137 feat: 맥주 요청 목록 api 연동
  src/apis/request-beer/get-request-beers.ts
  src/apis/request-beer/index.ts
  src/apis/request-beer/request-beer.ts
  src/components/RequestedBeerItem/RequestedBeerItem.stories.tsx
  src/components/RequestedBeerItem/RequestedBeerItem.tsx
  src/constants/page-titles.ts
  src/containers/BeerRequestContainer/BeerRequestContainer.tsx
  src/containers/BeerRequestListContainer/BeerRequestListContainer.stories.tsx
  src/containers/BeerRequestListContainer/BeerRequestListContainer.tsx
  src/containers/BeerRequestListContainer/index.ts
  src/containers/ProfileContainer/ProfileContainer.tsx
  src/pages/beer/requests.tsx
  src/queries/index.ts
  src/queries/useGetRequestBeers.ts
Labels: ✨ new feature

#152 feat: :sparkles: 업로드한 이미지 흑백처리
  src/components/BeerTicketTitle/BeerTicketTitle.tsx
  src/components/RecordListItem/RecordListItem.tsx
Labels: awesome beerair

#157 feat: :sparkles: ErrorBoundary 컴포넌트 구현
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ErrorBoundary/ErrorPage.stories.tsx
  src/components/ErrorBoundary/ErrorPage.tsx
  src/components/ErrorBoundary/index.ts
  src/pages/_app.tsx
Labels: awesome beerair

#175 fix: :bug: 저장하기 버튼 두번째 이상 눌렀을 때 저장 모달이 발생하지 않는 이슈 수정
  src/containers/RecordTicketContainer/CreateImage.tsx
Labels: 🐛 bug

#177 fix: :bug: 티켓 등록할 때 긴 텍스트 UI로 수정
  src/components/BeerTicket/BeerTicket.tsx
Labels: 🐛 bug

#178 fix: :bug: 맥주 상세페이지 댓글 무한스크롤 getNextPagePararm 수정
  src/queries/useGetRecordsByBeer.ts
Labels: 🐛 bug

#179 fix: :bug: BottomFloatingButtonArea로 인한 컨텐츠 가림 문제 수정
  src/components/BottomFloatingButtonArea/BottomFloatingButtonArea.tsx
Labels: 🐛 bug

#180 fix: :bug: outilne에 border-radius 적용안되는 문제 수정 (outline -> box-shadow)
  src/components/commons/Button/Button.tsx
Labels: 🐛 bug

#182 feat: :sparkles: ticket footer 고정
  src/components/BeerTicket/BeerTicket.tsx
  src/components/HomeBeerTicket/HomeBeerTicket.tsx
Labels: awesome beerair

#185 fix: 자잘한 ui 버그 수정
  src/components/AirPort/AirPort.tsx
  src/components/ReviewList/ReviewList.tsx
  src/components/beerItem/BeerGridItem/BeerGridItem.tsx
  src/containers/BeerDetailContainer/BeerDetailContainer.tsx
Labels: 🐛 bug

#194 fix: :bug: maxLength 체크 시 상태값을 사용하지 않고 event 값 사용
  src/containers/SignUpContainer/SignUpContainer.tsx
Labels: 🐛 bug

#196 feat: 게스트용 홈 UI 추가
  src/assets/arrow_right.svg
  src/assets/chevron_right.svg
  src/assets/icon.ts
  src/components/LoginRequestModal/LoginRequestModal.tsx
  src/components/Modal/Modal.tsx
  src/containers/HomeContainer/HomeContainer.tsx
  src/containers/HomeContainer/HomeSearchBar.tsx
  src/containers/OnBoardingContainer/OnBoardingContainer.tsx
  src/containers/UpsertRecordContainer/RecordSecondStepContainer/RecordSecondStepContainer.tsx
  src/containers/UpsertRecordContainer/RecordThirdStepContainer/RecordThirdStepContainer.tsx
  src/hocs/hasAuth.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/queries/useGetMyRecords.ts
Labels: ✨ new feature

#204 docs: :memo: README.md 초안 작성
  README.md
Labels: 📖 documentation

#210 fix: :bug: HomeSearchBar align-items: center css 추가
  src/containers/HomeContainer/HomeSearchBar.tsx
Labels: 🐛 bug
