Repository depromeet/sulsul-FE, pull requests merged in 2022-07, with the labels that each got.

#224 fix: 💄 빈 이모지 제거
  src/components/Emoji/Emoji.tsx
Labels: style

#218 fix: :beers: 공개여부 true default로 변경, 다음 -> 완료 수정
  src/containers/UpsertRecordContainer/RecordThirdStepContainer/RecordThirdStepContainer.tsx
Labels: awesome beerair

#217 docs: :beers: awsome android 다운로드 버튼 추가^^
  README.md
Labels: awesome beerair

#227 fix: 🐛 맥주 목록 버벅이는 문제, 맥주 목록 뒤로가기 버튼 제거
  src/components/BeerListPageHeader/BeerListPageHeader.tsx
  src/containers/BeerListContainer/BeerListContainer.tsx
  src/containers/BeerListContainer/recoil/atoms/beerListSortBy.ts
  src/queries/useGetBeers.ts
Labels: 🐛 bug
