Repository depromeet/sulsul-FE, pull requests merged in 2022-05, with the labels that each got.

#12 feat: :sparkles: 폰트 시스템 추가
  .storybook/preview.js
  package.json
  src/components/Sample/Sample.tsx
  src/pages/_app.tsx
  src/themes/Color.stories.tsx
  src/themes/Font.stories.tsx
  src/themes/GlobalStyle.tsx
  src/themes/fonts.ts
  src/themes/index.ts
  src/themes/types.ts
  yarn.lock
Labels: ✨ new feature

#15 feat: :sparkles: BeerStyleFilterItem 추가
  src/assets/check.svg
  src/assets/icon.ts
  src/components/filter/BeerStyleFilterItem/BeerStyleFilterItem.stories.tsx
  src/components/filter/BeerStyleFilterItem/BeerStyleFilterItem.tsx
  src/components/filter/BeerStyleFilterItem/index.ts
  src/styles/common.ts
Labels: ✨ new feature

#4 feature: BeerListItem, BeerGridItem 추가
  src/components/Emoji/Emoji.tsx
  src/components/beerItem/BeerGridItem/BeerGridItem.tsx
  src/components/beerItem/BeerListItem/BeerListItem.tsx
Labels: ✨ new feature, good first PR

#20 feature: Badge 컴포넌트, TasteBox 컴포넌트 추가
  package.json
  src/.DS_Store
  src/assets/icon.ts
  src/assets/like.svg
  src/components/TasteBoxAndBadge/TasteBoxAndBadge.stories.tsx
  src/components/TasteBoxAndBadge/TasteBoxAndBadge.tsx
  src/components/TasteBoxAndBadge/index.ts
  src/components/commons/Badge/Badge.stories.tsx
  src/components/commons/Badge/Badge.tsx
  src/components/commons/Badge/index.ts
  src/components/commons/LikeBadge/LikeBadge.stories.tsx
  src/components/commons/LikeBadge/LikeBadge.tsx
  src/components/commons/LikeBadge/index.ts
  src/components/commons/MeBadge/MeBadge.stories.tsx
  src/components/commons/MeBadge/MeBadge.tsx
  src/components/commons/MeBadge/index.ts
  src/components/commons/TasteBox/TasteBox.stories.tsx
  src/components/commons/TasteBox/TasteBox.tsx
  src/components/commons/TasteBox/index.ts
  tsconfig.json
  yarn.lock
Labels: ✨ new feature

#32 feat: ✨TextAreaField 컴포넌트 구현
  src/components/formFields/TextAreaField/TextAreaField.stories.tsx
  src/components/formFields/TextAreaField/TextAreaField.tsx
  src/components/formFields/TextAreaField/index.ts
Labels: ✨ new feature

#31 feature: MultiSelect 및 field 컴포넌트 구현
  .eslintrc
  src/components/ErrorMessage/ErrorMessage.stories.tsx
  src/components/ErrorMessage/ErrorMessage.tsx
  src/components/ErrorMessage/index.ts
  src/components/commons/TasteBox/TasteBox.tsx
  src/components/formFields/MultiSelectField/MultiSelect.stories.tsx
  src/components/formFields/MultiSelectField/MultiSelect.tsx
  src/components/formFields/MultiSelectField/MultiSelectField.tsx
  src/components/formFields/MultiSelectField/index.ts
  src/themes/Color.stories.tsx
  src/themes/index.ts
  src/themes/types.ts
  src/types/select.d.ts
Labels: ✨ new feature

#30 feature: Tab 컴포넌트 추가
  package.json
  src/components/Swiper/Swiper.stories.tsx
  src/components/Swiper/Swiper.tsx
  src/components/Swiper/index.ts
  src/components/Tab/Tab.stories.tsx
  src/components/Tab/Tab.tsx
  src/components/Tab/index.ts
  yarn.lock
Labels: ✨ new feature

#25 feat: ✨ BeerList 컴포넌트 추가, BeerImageMasking 컴포넌트 추가
  src/.DS_Store
  src/components/BeerDetail/BeerDetail.tsx
  src/components/BeerList/BeerList.stories.tsx
  src/components/BeerList/BeerList.tsx
  src/components/BeerList/index.ts
  src/components/Emoji/Emoji.tsx
  src/components/beerItem/BeerGridItem/BeerGridItem.stories.tsx
  src/components/beerItem/BeerGridItem/BeerGridItem.tsx
  src/components/beerItem/BeerListItem/BeerListItem.stories.tsx
  src/components/beerItem/BeerListItem/BeerListItem.tsx
  src/components/commons/BeerImageMasking/BeerImageMasking.stories.tsx
  src/components/commons/BeerImageMasking/BeerImageMasking.tsx
  src/components/commons/BeerImageMasking/index.ts
  src/constants/Beers.ts
  src/types/Beer.ts
Labels: ✨ new feature

#24 feat: :sparkles: Icon 컴포넌트 추가
  src/assets/home.svg
  src/assets/icon.ts
  src/assets/photo.svg
  src/components/Emoji/Emoji.tsx
  src/components/commons/HomeIconButton/HomeIconButton.stories.tsx
  src/components/commons/HomeIconButton/HomeIconButton.tsx
  src/components/commons/HomeIconButton/index.ts
  src/components/commons/Icon/Icon.stories.tsx
  src/components/commons/Icon/Icon.tsx
  src/components/commons/Icon/index.ts
  src/components/commons/Icon/svg/index.tsx
  src/components/commons/IconButton/IconButton.stories.tsx
  src/components/commons/IconButton/IconButton.tsx
  src/components/commons/IconButton/index.ts
  src/components/commons/PhotoIconButton/PhotoIconButton.stories.tsx
  src/components/commons/PhotoIconButton/PhotoIconButton.tsx
  src/components/commons/PhotoIconButton/index.ts
  src/utils/getEmoji.tsx
  src/utils/index.ts
Labels: ✨ new feature

#35 feat: 헤더 컴포넌트 추가
  .storybook/main.js
  __mocks__/next/image.js
  __mocks__/next/link.js
  __mocks__/next/router.js
  src/assets/back.svg
  src/assets/grid-view.svg
  src/assets/heart-outlined.svg
  src/assets/heart.svg
  src/assets/icon.ts
  src/assets/list-view.svg
  src/assets/save.svg
  src/assets/share.svg
  src/assets/write.svg
  src/assets/x.svg
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.tsx
  src/components/Header/extras/BackButton.tsx
  src/components/Header/extras/BaseIconButton.tsx
  src/components/Header/extras/CloseButton.tsx
  src/components/Header/extras/LikeToggleButton.tsx
  src/components/Header/extras/ListViewToggleButton.tsx
  src/components/Header/extras/OKTextButton.tsx
  src/components/Header/extras/SaveButton.tsx
  src/components/Header/extras/ShareButton.tsx
  src/components/Header/extras/WriteButton.tsx
  src/components/Header/extras/extras.stories.tsx
  src/components/Header/extras/index.tsx
  src/components/Header/index.ts
Labels: ✨ new feature

#38 feat: 맥주 필터 바텀시트 추가
  src/assets/x.svg
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Chip/Chip.tsx
  src/components/filter/BeerCountryFilterItem/BeerCountryFilterItem.tsx
  src/components/filter/BeerCountryFilterItem/index.ts
  src/components/filter/BeerCountryFilterList/BeerCountryFilterList.stories.tsx
  src/components/filter/BeerCountryFilterList/BeerCountryFilterList.tsx
  src/components/filter/BeerCountryFilterList/index.ts
  src/components/filter/BeerStyleFilterItem/BeerStyleFilterItem.tsx
  src/components/filter/BeerStyleFilterList/BeerStyleFilterList.stories.tsx
  src/components/filter/BeerStyleFilterList/BeerStyleFilterList.tsx
  src/components/filter/BeerStyleFilterList/index.ts
  src/components/filter/FilterBottomSheet/FilterBottomSheet.stories.tsx
  src/components/filter/FilterBottomSheet/FilterBottomSheet.tsx
  src/components/filter/FilterBottomSheet/index.ts
  src/components/filter/FilterFooter/FilterFooter.tsx
Labels: ✨ new feature

#39 feat: 맥주 리스트 필터 마크업
  src/assets/check.svg
  src/assets/icon.ts
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Chip/Chip.stories.tsx
  src/components/Chip/Chip.tsx
  src/components/Chip/index.ts
  src/components/Swiper/Swiper.tsx
  src/components/Tab/Tab.tsx
  src/components/filter/BeerCountryFilterItem/BeerCountryFilterItem.stories.tsx
  src/components/filter/BeerCountryFilterItem/BeerCountryFilterItem.tsx
  src/components/filter/BeerCountryFilterItem/index.ts
  src/components/filter/BeerCountryFilterList/BeerCountryFilterList.stories.tsx
  src/components/filter/BeerCountryFilterList/BeerCountryFilterList.tsx
  src/components/filter/BeerCountryFilterList/index.ts
  src/components/filter/BeerFilterBottomSheet/BeerFilterBottomSheet.stories.tsx
  src/components/filter/BeerFilterBottomSheet/BeerFilterBottomSheet.tsx
  src/components/filter/BeerFilterBottomSheet/index.ts
  src/components/filter/BeerStyleFilterItem/BeerStyleFilterItem.stories.tsx
  src/components/filter/BeerStyleFilterItem/BeerStyleFilterItem.tsx
  src/components/filter/BeerStyleFilterItem/index.ts
  src/components/filter/BeerStyleFilterList/BeerStyleFilterList.stories.tsx
  src/components/filter/BeerStyleFilterList/BeerStyleFilterList.tsx
  src/components/filter/BeerStyleFilterList/index.ts
  src/components/filter/FilterChipList/FilterChipList.stories.tsx
  src/components/filter/FilterChipList/FilterChipList.tsx
  src/components/filter/FilterChipList/index.ts
  src/components/filter/FilterFooter/FilterFooter.stories.tsx
  src/components/filter/FilterFooter/FilterFooter.tsx
  src/components/filter/FilterFooter/index.ts
  src/styles/common.ts
Labels: ✨ new feature

#50 feat: 맥주 목록 페이지 헤더 추가
  src/assets/icon.ts
  src/assets/x_circle.svg
  src/components/BeerListPageHeader/BeerListPageHeader.stories.tsx
  src/components/BeerListPageHeader/BeerListPageHeader.tsx
  src/components/BeerListPageHeader/index.ts
  src/components/commons/Icon/svg/index.tsx
  src/styles/common.ts
Labels: ✨ new feature

#45 feature: 💄 BeerDetail 페이지 마크업
  src/.DS_Store
  src/assets/flying_airplane.svg
  src/components/AirPort/AirPort.tsx
  src/components/AirPort/index.ts
  src/components/BeerDetail/BeerDetail.stories.tsx
  src/components/BeerDetail/BeerDetail.tsx
  src/components/BeerDetail/index.ts
  src/components/Header/Header.tsx
  src/components/Review/Review.tsx
  src/components/Review/index.ts
  src/components/TasteBoxAndBadge/TasteBoxAndBadge.tsx
  src/components/TasteBoxAndBadge/index.ts
  src/components/commons/BeerImageMasking/BeerImageMasking.tsx
  src/components/commons/Icon/Icon.tsx
  src/components/commons/LikeBadge/LikeBadge.tsx
  src/components/commons/TasteBox/TasteBox.tsx
  src/constants/Beers.ts
  src/constants/Reviews.ts
  src/constants/TasteBoxAndBadge.ts
  src/containers/BeerDetailContainer/BeerDetailContainer.stories.tsx
  src/containers/BeerDetailContainer/BeerDetailContainer.tsx
  src/containers/BeerDetailContainer/index.ts
  src/pages/beer/[id].tsx
  src/themes/index.ts
  src/themes/types.ts
  src/types/Beer.ts
Labels: ✨ new feature

#52 feat: :sparkles: Modal 컴포넌트 구현
  src/assets/close.svg
  src/assets/icon.ts
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/index.ts
  src/components/commons/Button/Button.stories.tsx
  src/components/commons/Button/Button.tsx
  src/components/commons/Icon/svg/index.tsx
Labels: ✨ new feature

#73 awesome: ⚡️브라우저 열었을때, 서버켰을때 이쁜 글씨 출력하기^^
  package.json
  src/pages/_app.tsx
  src/utils/awesome.ts
  yarn.lock
Labels: awesome beerair
